name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install project with uv
        run: |
          uv venv --python ${{ matrix.python-version }}
          uv pip install -e .

      - name: Run tests (uv)
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          uv run pytest
